name: helm-test
description: "Lint and test helm charts"

runs:
  using: composite
  steps:
      - name: Run chart-testing (lint)
        shell: bash
        run: ct lint --config $GITHUB_ACTION_PATH/ct-lint.yaml

      - name: Create kind cluster
        uses: Updater/kind-action@v1.2.0
        if: steps.setup.outputs.changed == 'true'

      - name: Apply CRDs
        if: steps.setup.outputs.changed == 'true'
        shell: bash
        run: |
          for crd in $GITHUB_ACTION_PATH/crds/*.yaml ; do
            kubectl apply -f $crd
          done

      - name: Configure cluster
        if: steps.setup.outputs.changed == 'true'
        shell: bash
        run: |
          kubectl create namespace istio-system

      - name: Run chart-testing (install)
        if: steps.setup.outputs.changed == 'true'
        shell: bash
        run: |
            ct install --config $GITHUB_ACTION_PATH/ct-install.yaml